version: '3.8'

services:
  web:
    image: mmaker:latest
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  db:
    platform: "linux/amd64"
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: matchmaker
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
